<x-header :title='__("cookie.pageTitle") . " | Eztem Corp"' :metadescription='__("cookie.metadescription")' :canonical='__("cookie.canonical")' />

{{-- Pagina "Cookie" --}}{{-- Page "Cookie" --}}
<main>
    {{-- Sectiunea de Cookies --}}{{-- Section of Cookies --}}
    <div class="container notes__container">
        <div class="breadcrums">
            <a href="/" _target="_blank">
                @lang("components.breadcrums.Home")
            </a>
            <span> > </span>
            <a href="/web" _target="_blank">
                @lang("components.breadcrums.Cookie")
            </a>
        </div>
        <h1>
            @lang("cookie.cookie.heading")
        </h1>
        <ol class="category">
            <li>
                <h3>
                    @lang("cookie.cookie.category1.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("cookie.cookie.category1.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category1.item2")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category1.item3")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("cookie.cookie.category2.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("cookie.cookie.category2.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category2.item2")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category2.item3")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category2.item4")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("cookie.cookie.category3.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("cookie.cookie.category3.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category3.item2")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("cookie.cookie.category4.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <h3>
                            @lang("cookie.cookie.category4.sub_heading")
                        </h3>
                        <ol class="sub-sub-category">
                            <li>
                                <p>
                                    @lang("cookie.cookie.category4.item1")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category4.item2")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category4.item3")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category4.item4")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category4.item5")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category4.item6")
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>
                            @lang("cookie.cookie.category5.sub_heading")
                        </h3>
                        <ol class="sub-sub-category">
                            <li>
                                <p>
                                    @lang("cookie.cookie.category5.item1")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category5.item2")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category5.item3")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category5.item4")
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>
                            @lang("cookie.cookie.category6.sub_heading")
                        </h3>
                        <ol class="sub-sub-category">
                            <li>
                                <p>
                                    @lang("cookie.cookie.category6.item1")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category6.item2")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category6.item3")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category6.item4")
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>
                            @lang("cookie.cookie.category7.sub_heading")
                        </h3>
                        <ol class="sub-sub-category">
                            <li>
                                <p>
                                    @lang("cookie.cookie.category7.item1")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category7.item2")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category7.item3")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("cookie.cookie.category7.item4")
                                </p>
                            </li>
                        </ol>
                    </li>

                </ol>
            </li>
            <li>
                <h3>
                    @lang("cookie.cookie.category8.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("cookie.cookie.category8.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category8.item2")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("cookie.cookie.category8.item3")
                        </p>
                    </li>
                </ol>
            </li>
        </ol>
    </div>
</main>
<x-cookie />
<x-footer />
