<x-header :title='__("privacy.pageTitle") . " | Eztem Corp"' :metadescription='__("privacy.metadescription")' :canonical="url('/privacy')" />

<main>
    <div class="container notes__container">
        <div class="breadcrums">
            <a href="/" _target="_blank">
                @lang("components.breadcrums.Home")
            </a>
            <span> > </span>
            <a href="/privacy" _target="_blank">
                @lang("components.breadcrums.Privacy")
            </a>
        </div>
        <h1>
            @lang("privacy.privacy.heading")
        </h1>
        <p>
            @lang("privacy.privacy.description")
        </p>
        <ol class="category">
            <li>
                <h3>
                    @lang("privacy.privacy.category1.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category1.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category1.item2")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category2.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category2.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category2.item2")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category2.item3")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category2.item4")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category3.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category3.item1")
                        </p>
                        <ol class="sub-sub-category">
                            <li>
                                <p>
                                    @lang("privacy.privacy.category3.sub-item1")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category3.sub-item2")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category3.sub-item3")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category3.sub-item4")
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category3.item2")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category3.item3")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category3.item4")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category4.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category4.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category4.item2")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category4.item3")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category4.item4")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category5.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category5.item1")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category6.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category6.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category6.item2")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category7.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category7.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category7.item2")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category8.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category8.item1")
                        </p>
                        <ol class="sub-sub-category">
                            <li>
                                <p>
                                    @lang("privacy.privacy.category8.sub-item1")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category8.sub-item2")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category8.sub-item3")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category8.sub-item4")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category8.sub-item5")
                                </p>
                            </li>
                            <li>
                                <p>
                                    @lang("privacy.privacy.category8.sub-item6")
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category8.item2")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category8.item3")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category9.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category9.item1")
                        </p>
                    </li>
                </ol>
            </li>
            <li>
                <h3>
                    @lang("privacy.privacy.category10.heading")
                </h3>
                <ol class="sub-category">
                    <li>
                        <p>
                            @lang("privacy.privacy.category10.item1")
                        </p>
                    </li>
                    <li>
                        <p>
                            @lang("privacy.privacy.category10.item2")
                        </p>
                    </li>
                </ol>
            </li>
        </ol>
    </div>
</main>
<x-cookie />
<x-footer />
